-- Centralized notification module. Notifications are generated by
-- security-definer trigger functions on the underlying tables, so they
-- fire automatically no matter which page/flow performs the action —
-- not scattered client-side inserts that are easy to miss.

create table notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_id uuid not null references profiles(id) on delete cascade,
  type text not null,
  title text not null,
  message text,
  action_url text,
  entity_type text,
  entity_id uuid,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index idx_notifications_recipient on notifications(recipient_id, created_at desc);

alter table notifications enable row level security;

create policy "notifications_select_own" on notifications for select
  using (recipient_id = auth.uid());
create policy "notifications_update_own" on notifications for update
  using (recipient_id = auth.uid()) with check (recipient_id = auth.uid());

-- No insert policy: all rows are written by the security-definer
-- trigger functions below, which bypass RLS as the function owner.

create function notify(
  p_recipient uuid,
  p_type text,
  p_title text,
  p_message text,
  p_action_url text default null,
  p_entity_type text default null,
  p_entity_id uuid default null
) returns void
language plpgsql security definer set search_path = public
as $$
begin
  if p_recipient is null then
    return;
  end if;
  insert into notifications (recipient_id, type, title, message, action_url, entity_type, entity_id)
  values (p_recipient, p_type, p_title, p_message, p_action_url, p_entity_type, p_entity_id);
end;
$$;

-- ============ Appointments: booked / assigned / confirmed / cancelled / completed / rescheduled / no-show ============
create function trg_appointment_notify()
returns trigger
language plpgsql security definer set search_path = public
as $$
declare
  when_text text;
  mgr record;
begin
  when_text := to_char(new.start_time, 'Mon DD, YYYY HH12:MI AM');

  if TG_OP = 'INSERT' then
    perform notify(new.customer_id, 'appointment_booked', 'Booking confirmed',
      'Your appointment on ' || when_text || ' has been booked.', '/dashboard/appointments', 'appointment', new.id);
    if new.staff_id is not null then
      perform notify(new.staff_id, 'appointment_assigned', 'New appointment assigned',
        'You have a new appointment on ' || when_text || '.', '/dashboard/my-work', 'appointment', new.id);
    end if;
    return new;
  end if;

  if TG_OP = 'UPDATE' then
    if new.status is distinct from old.status then
      if new.status = 'confirmed' then
        perform notify(new.customer_id, 'appointment_confirmed', 'Checked in',
          'You''re checked in for your appointment on ' || when_text || '.', '/dashboard/appointments', 'appointment', new.id);
      elsif new.status = 'cancelled' then
        perform notify(new.customer_id, 'appointment_cancelled', 'Appointment cancelled',
          'Your appointment on ' || when_text || ' was cancelled.', '/dashboard/appointments', 'appointment', new.id);
        if new.staff_id is not null then
          perform notify(new.staff_id, 'appointment_cancelled', 'Appointment cancelled',
            'The appointment on ' || when_text || ' was cancelled.', '/dashboard/my-work', 'appointment', new.id);
        end if;
      elsif new.status = 'completed' then
        perform notify(new.customer_id, 'appointment_completed', 'Thanks for visiting!',
          'We''d love your feedback — leave a review from your appointment history.', '/dashboard', 'appointment', new.id);
      elsif new.status = 'no_show' then
        for mgr in select id from profiles where branch_id is not distinct from new.branch_id and role in ('manager', 'admin') loop
          perform notify(mgr.id, 'appointment_no_show', 'No-show recorded',
            'A customer did not show up for their ' || when_text || ' appointment.', '/dashboard/appointments', 'appointment', new.id);
        end loop;
      end if;
    elsif new.start_time is distinct from old.start_time then
      perform notify(new.customer_id, 'appointment_rescheduled', 'Appointment rescheduled',
        'Your appointment is now on ' || when_text || '.', '/dashboard/appointments', 'appointment', new.id);
      if new.staff_id is not null then
        perform notify(new.staff_id, 'appointment_rescheduled', 'Schedule change',
          'An appointment was rescheduled to ' || when_text || '.', '/dashboard/my-work', 'appointment', new.id);
      end if;
    end if;
    return new;
  end if;

  return new;
end;
$$;

create trigger appointments_notify
  after insert or update on appointments
  for each row execute function trg_appointment_notify();

-- ============ Payments: received ============
create function trg_payment_notify()
returns trigger
language plpgsql security definer set search_path = public
as $$
declare
  cust uuid;
  inv_number text;
begin
  select customer_id, invoice_number into cust, inv_number from invoices where id = new.invoice_id;
  perform notify(cust, 'payment_received', 'Payment received',
    'We received your payment of $' || new.amount || ' for invoice ' || inv_number || '.',
    '/dashboard/billing', 'payment', new.id);
  return new;
end;
$$;

create trigger payments_notify
  after insert on payments
  for each row execute function trg_payment_notify();

-- ============ Invoices: generated / refunded ============
create function trg_invoice_notify()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  if TG_OP = 'INSERT' then
    perform notify(new.customer_id, 'invoice_generated', 'Invoice generated',
      'Invoice ' || new.invoice_number || ' for $' || new.total || ' has been generated.',
      '/dashboard/billing', 'invoice', new.id);
  elsif TG_OP = 'UPDATE' and new.status is distinct from old.status and new.status = 'refunded' then
    perform notify(new.customer_id, 'invoice_refunded', 'Refund processed',
      'Invoice ' || new.invoice_number || ' has been refunded.', '/dashboard/billing', 'invoice', new.id);
  end if;
  return new;
end;
$$;

create trigger invoices_notify
  after insert or update on invoices
  for each row execute function trg_invoice_notify();

-- ============ Products: low stock ============
create function trg_low_stock_notify()
returns trigger
language plpgsql security definer set search_path = public
as $$
declare
  mgr record;
begin
  if new.stock_qty <= new.reorder_level and (TG_OP = 'INSERT' or old.stock_qty > old.reorder_level) then
    for mgr in select id from profiles where branch_id is not distinct from new.branch_id and role in ('manager', 'admin') loop
      perform notify(mgr.id, 'low_stock', 'Low stock alert',
        new.name || ' is low on stock (' || new.stock_qty || ' left).', '/dashboard/inventory', 'product', new.id);
    end loop;
  end if;
  return new;
end;
$$;

create trigger products_stock_notify
  after insert or update on products
  for each row execute function trg_low_stock_notify();

-- ============ Leave requests: submitted / reviewed ============
create function trg_leave_notify()
returns trigger
language plpgsql security definer set search_path = public
as $$
declare
  mgr record;
  staff_name text;
begin
  if TG_OP = 'INSERT' then
    select full_name into staff_name from profiles where id = new.staff_id;
    for mgr in select id from profiles where branch_id is not distinct from new.branch_id and role in ('manager', 'admin') loop
      perform notify(mgr.id, 'leave_requested', 'New leave request',
        coalesce(staff_name, 'A staff member') || ' requested leave from ' || new.start_date || ' to ' || new.end_date || '.',
        '/dashboard', 'leave_request', new.id);
    end loop;
  elsif TG_OP = 'UPDATE' and new.status is distinct from old.status and new.status in ('approved', 'rejected') then
    perform notify(new.staff_id, 'leave_reviewed', 'Leave request ' || new.status,
      'Your leave request from ' || new.start_date || ' to ' || new.end_date || ' was ' || new.status || '.',
      '/dashboard/my-work', 'leave_request', new.id);
  end if;
  return new;
end;
$$;

create trigger leave_requests_notify
  after insert or update on leave_requests
  for each row execute function trg_leave_notify();

-- ============ Reviews: received ============
create function trg_review_notify()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  if new.staff_id is not null then
    perform notify(new.staff_id, 'review_received', 'New review received',
      'You received a ' || new.rating || '-star review.', '/dashboard/my-work', 'review', new.id);
  end if;
  return new;
end;
$$;

create trigger reviews_notify
  after insert on reviews
  for each row execute function trg_review_notify();

-- ============ Loyalty points: awarded ============
create function trg_loyalty_notify()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  if new.type = 'earn' and new.points > 0 then
    perform notify(new.customer_id, 'loyalty_earned', 'Loyalty points earned',
      'You earned ' || new.points || ' points.', '/dashboard', 'loyalty_transaction', new.id);
  end if;
  return new;
end;
$$;

create trigger loyalty_notify
  after insert on loyalty_transactions
  for each row execute function trg_loyalty_notify();

-- ============ Memberships: purchased ============
create function trg_membership_notify()
returns trigger
language plpgsql security definer set search_path = public
as $$
declare
  plan_name text;
  mgr record;
begin
  select name into plan_name from membership_plans where id = new.plan_id;
  perform notify(new.customer_id, 'membership_purchased', 'Membership activated',
    'Welcome to ' || coalesce(plan_name, 'your new') || ' membership!', '/dashboard', 'membership', new.id);
  for mgr in select id from profiles where role in ('manager', 'admin') loop
    perform notify(mgr.id, 'membership_sale', 'New membership sale',
      coalesce(plan_name, 'A membership') || ' plan was purchased.', '/dashboard/admin', 'membership', new.id);
  end loop;
  return new;
end;
$$;

create trigger memberships_notify
  after insert on customer_memberships
  for each row execute function trg_membership_notify();
